```{r}
library(plyr)
library(Hmisc)

#Read data

fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
download.file(fileURL,destfile="gdp.csv",method="curl")
gdp <- read.csv(file="gdp.csv",skip=5,stringsAsFactors = F, header = F)
gdp <- gdp[1:190, c(1, 2, 4, 5)]
names(gdp) <- c("CountryCode","Ranking","Economy","GDP")
gdp$GDP <- as.numeric(gsub(",", "", gdp$GDP))
gdp$Ranking <- as.numeric(gsub(",", "", gdp$Ranking))

fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
download.file(fileURL,destfile="getdata-data-EDSTATS_Country.cvs")
edstats <- read.csv(file="getdata-data-EDSTATS_Country.cvs", stringsAsFactors = F)

```

```{r}
#Question1:	Match the data based on the country shortcode. How many of the IDs match? 
new <- merge(gdp, edstats, by= "CountryCode")
nrow(new)

#Answer: After merged the data by contrycode, there are 189 IDs match.
```

```{r}
#Question2: Sort the data frame in ascending order by GDP rank (so United States is last). What is the 13th country in the resulting data frame?

new.ordered <- new[order(new$Ranking, decreasing = T),]
new.ordered[13,]$Economy

#Answer: The 13th country in the resulting data frame is St. Kitts and Nevis
```

```{r}
#Question3:	What are the average GDP rankings for the "High income: OECD" and "High income: nonOECD" groups?

mean.rank.oecd <- mean(new[which(new$Income.Group=="High income: OECD"),]$Ranking)
mean.rank.nonoecd <- mean(new[which(new$Income.Group=="High income: nonOECD"),]$Ranking)
mean.rank.oecd
mean.rank.nonoecd

#Answer: The average GDP rankings for the "High income:OECD" is 32.96667
#        The average GDP rankings for the "High income:nonOECD" is 91.91304
```

```{r}
#Question 4:Cut the GDP ranking into 5 separate quantile groups. Make a table versus Income.Group. How many countries are Lower middle income but among the 38 nations with highest GDP?

new$Ranking.factor <- cut2(new$Ranking, g = 5)
table(new$Income.Group, new$Ranking.factor)[1,4]

#Answer: There are 5 countries which are lower middle income but among the 38 nations with highest GDP.
```

```{r}
#Question 5: If you encounter NAs in your analysis, please delete those values and continue the analysis with the non-missing values. However, please include code to count the number of missing values for each variable used in the analysis.

#Answer: In the first dataset, I read the data without no NAs, and then create a new dataset by merging it with the second dataset. Although there are some NAs in the new dataset, they didn't get involved in the analysis so I didn't encounter any NAs.
```

